### ISSUE TITLE
Änderungen für DE84  werden nicht übernommen

### ISSUE THREAD

**Issue by jaohbib** [gbv/libsites-config#197]
Hallo 

Der Standort m8 macht Probleme
https://github.com/gbv/libsites-config/blob/master/isil/DE-84/sites.txt#L1039

https://uri.gbv.de/organization/isil/DE-84@m8

Der Name in der Config passt nicht zum Namen in der Anwendung  

@hornmo  Ist unsere Config korrekt ?

**Comment by nichtich** [comment]
Die Änderung wurde jetzt übernommen, wir bitten die Verzögerung zu entschuldigen!
